### ISSUE TITLE
Resource to add: https://getcssscan.com/css-buttons-examples

### ISSUE THREAD

**Issue by marcelscruz** [marcelscruz/dev-resources#130]
**URL:** https://getcssscan.com/css-buttons-examples

*This issue was automatically generated from the [website](https://devresourc.es).*

**Comment by guivr** [comment]
Hi! I've created a pull request

**Comment by marcelscruz** [comment]
Merged! :)

**Comment by guivr** [comment]
Awesome, thanks!
