### ISSUE TITLE
Resource to add: https://karim-portfolio.netlify.app/

### ISSUE THREAD

**Issue by marcelscruz** [marcelscruz/dev-resources#153]
**URL:** https://karim-portfolio.netlify.app/
**Message:** it's My Portfolio

*This issue was automatically generated from the [website](https://devresourc.es).*

**Comment by marcelscruz** [comment]
Hey! 
`community/personal-websites` would be the place for that! :)

**Comment by IEdiong** [comment]
Okay, that's cool. So, I'm guessing that it's going to be a collection of inspirational personal portfolio websites. If this is true then I would have a couple of those to contribute (I have been saving a couple of such in my bookmark).

**Comment by marcelscruz** [comment]
Exactly!

That category is a spot for all developers to showcase their own personal websites.

And feel free to add as many as you want, that's in fact greatly appreciated!
