### ISSUE TITLE
Resource to remove : Scotch.io 

### ISSUE THREAD

**Issue by samr1ddh1** [marcelscruz/dev-resources#201]
**Describe the bug**
Scotch.io the Resource mentioned in the "Learn Programming" Section has been discontinued ..as it has been acquired by Digital Ocean since Jan 2021.

**To Reproduce**
1. Go to 'https://www.devresourc.es/'
2. Click on 'Learn Programming'
3. Scroll down to 'Scotch'
4. Click 'Visit'
5. See error

**Comment by spencer1573** [comment]
PR #293 solves this issue. please let me know if you have any questions. thanks!

**Comment by marcelscruz** [comment]
Thanks!
