### ISSUE TITLE
Regarding the current situation of the Public APIs project 

### ISSUE THREAD

**Issue by pawelborkar** [marcelscruz/dev-resources#211]
Hi @marcelscruz ,
Hope your doing good. This issue is regarding the current situation which we the collaborators at [Public APIs](https://github.com/public-apis/public-apis/issues/3104) are facing  regarding the future of public apis and the open source community in general.

As we've added your website in one of the unofficial list of websites in the readme, there's a possibility of a number of people visiting it. So it's one of the reasons I'm writing this issue. In order to bring this issue in front of the community members  

Please read [this](https://github.com/public-apis/public-apis/issues/3104) issue and we would encourage you to spread it on your website's homepage or write blogs or a tweet about it in order to bring this serious issue into the limelight of the community members. And help the project to survive.

Thanks, 
Pawel

**Comment by marcelscruz** [comment]
Hi Pawel.

Thank you for reaching out and letting me know of the current situation with the Public APIs project.

It saddens me to know that such an amazing **community-based** project is being wrongly used by their owners, plus the disregard for the maintainers. I'm sorry to hear it.

Public APIs is a big part of Dev Resources and I'm more than happy to help you however I can.

I think as a first measure I can put a banner on the website to let its users know of the current situation, but what exactly are we trying to convey in this message? How can we ask for their support?

I can bring up the topic on Twitter and our Discord group, though I don't think I'll have much reach there.

As far as I understand, the current owners of Public APIs are not even responding, so is there any hope in keeping the current project going? Or are you thinking of forking/migrating to a new repo?

Also, if you have any other ideas of how I or Dev Resources can be of any help, please let me know.

We're in this together.

**Comment by pawelborkar** [comment]
>I think as a first measure I can put a banner on the website to let its users know of the current situation, but what exactly are we trying to convey in this message? How can we ask for their support?

Yes, We think that redirecting to the issue will create a traction in the community and make the community members aware about  the current situation we're facing at Public APIs. As it's one of the biggest open source project it is possible that if the community members starts discussing about it openly by creating tweets, blogs or videos about the current situation and the behaviour of the APILayer company such that the management at APILayer may reconsider their decision and give the rights we deserve which will help us to revive the project and foster the community around it. Otherwise It'll gonna halted as such it was a year ago please see [this](https://github.com/public-apis/public-apis/issues/1268) for more and soon be dead again. 

> How can we ask for their support?

We can ask for their support by asking them to talk and discuss this issue publicly that's what we all can do as of know. 

>I can bring up the topic on Twitter and our Discord group, though I don't think I'll have much reach there.

Yeah sure that would be very useful.

>As far as I understand, the current owners of Public APIs are not even responding, so is there any hope in keeping the current project going? Or are you thinking of forking/migrating to a new repo?

As the project has so much of traction and it ranks way higher in the SEO and has a greater reach and also has been shared by a lot of community members we considering every possible way which will help us to keep the current project going.

>Also, if you have any other ideas of how I or Dev Resources can be of any help, please let me know.

Yeah sure.

>We're in this together.

Thanks you so much for your support Marcel. We appreciate it.
