### ISSUE TITLE
Add TraderMade Data API

### ISSUE THREAD

**Issue by rahulkhn** [marcelscruz/dev-resources#291]
Please add Tradermade Forex and CFD data API to your list of finance public API - this is one of the only few APIs that provides live CFD data for free - link to the website is tradermade.com

**Comment by marcelscruz** [comment]
Hi @rahulkhn.
The public APIs list lives in a [different repository](https://github.com/public-apis-dev/public-apis), so please feel free to [make a contribution](https://github.com/public-apis-dev/public-apis/blob/main/CONTRIBUTING.md) there.
