### ISSUE TITLE
Add Dev Utils

### ISSUE THREAD

**Issue by lucgagan** [marcelscruz/dev-resources#336]
Would like to add:

* https://devutils.com/
* https://ray.run/tools

But not clear which section it should go to. What do you suggest?

**Comment by lucgagan** [comment]
also Playwright is missing from testing section

**Comment by marcelscruz** [comment]
Hi @lucgagan, I think the best places are "Programming" and "Productivity".
They are tools that do a lot, so hard to pinpoint one exact category.
Thank you for the suggestion, btw!
