### ISSUE TITLE
Order Selection

### ISSUE THREAD

**Issue by srshankar145** [marcelscruz/dev-resources#355]
**Describe the bug**
Is it possible to change the font color of the Order menu item so that they are visible without having to choose an item first, as the current font color is white and causes visibility issues?

**To Reproduce**
1. Go to Any category
2. Click on Order menu item
3. See error

**Expected behavior**
If its choosen then we can see the menu item, otherwise its not visible. 

**Screenshots**
![image](https://github.com/marcelscruz/dev-resources/assets/4988596/d4459896-b088-47c1-8e5a-a95386631cc1)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [e.g. 117]

**Comment by marcelscruz** [comment]
Thank you for reporting it!
The bug is now fixed.

<img width="216" alt="Screenshot 2023-10-01 at 17 15 58" src="https://github.com/marcelscruz/dev-resources/assets/12413903/4cf25a32-d91c-4039-9c0a-96a5fce85cf7">

**Comment by srshankar145** [comment]
Thanks Marcel...
